server:
  port: ${port:8080}

spring:
  datasource:
    driver-class-name: ${jdbc_driver:com.mysql.jdbc.Driver}
    url: ${jdbc_url:jdbc:mysql://mysql:3306/eap_bpm?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false}
    username: ${jdbc_user:root}
    password: ${jdbc_password:root}
    dbType: ${db_type:mysql}
  activemq:
    broker-url: ${activemq_url:tcp://127.0.0.1:61616}
    in-memory: false
    packages:
      trust-all: true
  redis:
    host: ${redis_host:redis}
    port: ${redis_port:6379}
    password: ${redis_password:}
    database: ${redis_database:0}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    org.springframework.data.redis: INFO

## security:
##  ignored:  [/bpm-ui/** ,/css/**, /js/**,/images/**,/webjars/**,/**/favicon.ico]
## /swagger-*,/v2/api-docs*,   swagger 免登陆
eap:
  jwt:
    enabled: false
  security:
    auth-ingores: /login.*,/bpm-ui*,/index.html,/swagger-*,/v2/api-docs*,
  redis:
    use-redis-cache: true
  mail:
    mail-address: xxx@qq.com
    nick-name: open-bpm
    password: xxx
    send-host: smtp.qq.com
    send-port: 465
  simple-mq:
    message-queue-type: synchronous

ab:
  jwt:
    enabled: false
  security:
    auth-ingores: /login.*,/bpm-ui*,/index.html,/swagger-*,/v2/api-docs*,
  redis:
    use-redis-cache: true
  mail:
    mail-address: xxx@qq.com
    nick-name: open-bpm
    password: xxx
    send-host: smtp.qq.com
    send-port: 465
  simple-mq:
    message-queue-type: synchronous


## 上传配置 db 存数据库 ，具体请看 IUploader 实现类
uploader:
  default: db